//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoritmApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamer
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public Nullable<int> TryId { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Try Try { get; set; }
    }
}
